
import React from 'react';
import { 
  MessageSquare, BookOpen, Briefcase, User, Calendar, 
  BarChart, Users, Smartphone, FileText, Lightbulb, 
  Package, Bike, Shirt, Palmtree, 
  Building, Cpu, Palette, Share2, Plus, Zap, Star,
  Target, PenTool, Layers, Repeat, Trophy, Compass, Eye, Shield
} from 'lucide-react';
import { Template, Example } from './types';

export const AI_OPTIONS = [
  { name: 'ChatGPT', color: 'bg-emerald-500', icon: '🤖' },
  { name: 'Gemini', color: 'bg-blue-500', icon: '✨' },
  { name: 'Claude', color: 'bg-orange-500', icon: '🧠' },
  { name: 'Midjourney', color: 'bg-indigo-500', icon: '🎨' },
  { name: 'DALL-E', color: 'bg-rose-500', icon: '👁️' },
  { name: 'Stable Diffusion', color: 'bg-purple-500', icon: '🌀' },
];

export const TEXT_CATEGORIES = [
  { id: 'emails', name: 'E-mails e mensagens', icon: <MessageSquare size={20} /> },
  { id: 'estudos', name: 'Estudos e aprendizado', icon: <BookOpen size={20} /> },
  { id: 'trabalho', name: 'Trabalho e produtividade', icon: <Briefcase size={20} /> },
  { id: 'marketing', name: 'Marketing e conteúdo', icon: <BarChart size={20} /> },
  { id: 'vendas', name: 'Vendas e atendimento', icon: <Users size={20} /> },
  { id: 'social', name: 'Redes sociais', icon: <Smartphone size={20} /> },
  { id: 'outro', name: 'Outro', icon: <Plus size={20} /> },
];

export const IMAGE_TYPES = [
  { id: 'pessoa', name: 'Pessoa', icon: <User size={20} /> },
  { id: 'produto', name: 'Produto', icon: <Package size={20} /> },
  { id: 'paisagem', name: 'Paisagens', icon: <Palmtree size={20} /> },
  { id: 'arquitetura', name: 'Arquitetura', icon: <Building size={20} /> },
  { id: 'arte', name: 'Arte conceitual', icon: <Palette size={20} /> },
  { id: 'outro', name: 'Outro', icon: <Plus size={20} /> },
];

export const TEMPLATES: Template[] = [
  // --- 75 TEXT TEMPLATES ---
  { id: 't1', title: 'Copy AIDA Premium', type: 'text', preview: 'Marketing', prompt: 'Atue como um Copywriter Sênior. Use o framework AIDA (Atenção, Interesse, Desejo, Ação) para criar uma oferta irresistível para [PRODUTO].' },
  { id: 't2', title: 'LinkedIn Thought Leader', type: 'text', preview: 'Social', prompt: 'Crie um post para o LinkedIn no estilo "autoridade". Comece com uma frase polêmica sobre [TEMA] e termine com uma lição valiosa.' },
  { id: 't3', title: 'Explicação Feynman', type: 'text', preview: 'Estudos', prompt: 'Explique [ASSUNTO COMPLEXO] usando a técnica Feynman (como se eu tivesse 10 anos). Use analogias simples.' },
  { id: 't4', title: 'Resumo Executivo', type: 'text', preview: 'Trabalho', prompt: 'Resuma o conteúdo abaixo em 3 parágrafos focados em tomada de decisão e impacto financeiro: [TEXTO].' },
  { id: 't5', title: 'Cold Email B2B', type: 'text', preview: 'Vendas', prompt: 'Escreva um e-mail de prospecção fria para um Diretor de [SETOR]. O tom deve ser breve, curioso e focado no benefício X.' },
  { id: 't6', title: 'Gancho de Vídeo Viral', type: 'text', preview: 'Social', prompt: 'Gere 5 opções de ganchos (hooks) para um vídeo de 60 segundos sobre [TEMA]. Foco em retenção imediata.' },
  { id: 't7', title: 'Script de Vendas WhatsApp', type: 'text', preview: 'Vendas', prompt: 'Crie um script de quebra de objeção para um cliente que disse "está caro" para o [PRODUTO]. Use empatia.' },
  { id: 't8', title: 'SEO Meta Description', type: 'text', preview: 'Marketing', prompt: 'Escreva 3 opções de Meta Description (máx 160 caracteres) para a palavra-chave [KEYWORD]. Foco em CTR.' },
  { id: 't9', title: 'Plano de Estudo 30 Dias', type: 'text', preview: 'Estudos', prompt: 'Crie um cronograma detalhado de 30 dias para dominar [HABILIDADE]. Divida em blocos de 1h por dia.' },
  { id: 't10', title: 'Storytelling de Marca', type: 'text', preview: 'Marketing', prompt: 'Crie a narrativa da "Jornada do Herói" para a marca [NOME DA MARCA]. Foque na transformação do cliente.' },
  { id: 't11', title: 'Tradução Cultural', type: 'text', preview: 'Outro', prompt: 'Traduza o texto abaixo para [IDIOMA], mas adapte as gírias e referências culturais para o público local: [TEXTO].' },
  { id: 't12', title: 'Refatoração de Código', type: 'text', preview: 'Trabalho', prompt: 'Refatore o seguinte código para torná-lo mais legível, eficiente e seguindo os princípios Clean Code: [CÓDIGO].' },
  { id: 't13', title: 'Ideias de Newsletter', type: 'text', preview: 'Marketing', prompt: 'Sugira 5 temas de edições para uma newsletter semanal sobre [NICHOS]. Inclua linhas de assunto clicáveis.' },
  { id: 't14', title: 'FAQ de Produto', type: 'text', preview: 'Vendas', prompt: 'Gere as 10 perguntas mais comuns que um cliente teria sobre [PRODUTO] e responda de forma persuasiva.' },
  { id: 't15', title: 'Roteiro de Podcast', type: 'text', preview: 'Marketing', prompt: 'Escreva um roteiro de introdução para um podcast sobre [TEMA]. O tom deve ser energético e envolvente.' },
  { id: 't16', title: 'Análise SWOT', type: 'text', preview: 'Trabalho', prompt: 'Realize uma análise SWOT (Forças, Fraquezas, Oportunidades, Ameaças) para o negócio [TIPO DE NEGÓCIO].' },
  { id: 't17', title: 'Roteiro de Webinar', type: 'text', preview: 'Vendas', prompt: 'Crie a estrutura de um webinar de 45 minutos para vender [PRODUTO]. Do problema à oferta irresistível.' },
  { id: 't18', title: 'Descrição de App Store', type: 'text', preview: 'Marketing', prompt: 'Escreva uma descrição otimizada para a App Store para um app de [TIPO]. Use emojis e bullet points.' },
  { id: 't19', title: 'Carta de Resignação', type: 'text', preview: 'Trabalho', prompt: 'Escreva uma carta de demissão profissional e grata para a empresa [NOME]. Deixe as portas abertas.' },
  { id: 't20', title: 'Bio de Instagram Profissional', type: 'text', preview: 'Social', prompt: 'Crie 3 opções de biografias para Instagram para um [PROFISSÃO]. Use autoridade e um CTA claro.' },
  { id: 't21', title: 'Preparação para Entrevista', type: 'text', preview: 'Estudos', prompt: 'Liste as 5 perguntas mais difíceis para uma vaga de [CARGO] e sugira respostas baseadas em resultados.' },
  { id: 't22', title: 'Script de Cold Call', type: 'text', preview: 'Vendas', prompt: 'Escreva um roteiro de 30 segundos para uma ligação de prospecção focada em agendar uma reunião.' },
  { id: 't23', title: 'Anúncio Google Ads', type: 'text', preview: 'Marketing', prompt: 'Gere 3 variações de títulos (30 carac) e descrições (90 carac) para um anúncio de [PRODUTO].' },
  { id: 't24', title: 'Roteiro TikTok Educativo', type: 'text', preview: 'Social', prompt: 'Crie um roteiro de "Dica Rápida" para TikTok. Tempo: 30s. Estilo dinâmico com cortes rápidos.' },
  { id: 't25', title: 'Sumário Executivo Financeiro', type: 'text', preview: 'Trabalho', prompt: 'Analise os dados financeiros abaixo e extraia os 5 principais insights para investidores: [DADOS].' },
  { id: 't26', title: 'Reescrita de Texto Formal', type: 'text', preview: 'Trabalho', prompt: 'Reescreva o parágrafo abaixo para torná-lo mais diplomático e executivo, sem perder o sentido original.' },
  { id: 't27', title: 'Ideias de Isca Digital', type: 'text', preview: 'Marketing', prompt: 'Sugira 3 tipos de materiais gratuitos (Ebooks, Checklists, etc) que atrairiam clientes para [SERVIÇO].' },
  { id: 't28', title: 'Ghostwriter de Blog Post', type: 'text', preview: 'Marketing', prompt: 'Escreva um post de blog de 1000 palavras sobre [TEMA]. Use SEO, subtítulos e um tom de especialista.' },
  { id: 't29', title: 'Crítica de Texto', type: 'text', preview: 'Estudos', prompt: 'Atue como um editor literário. Aponte 3 pontos fracos e 3 pontos fortes no texto a seguir: [TEXTO].' },
  { id: 't30', title: 'Ideias de Reels Tendência', type: 'text', preview: 'Social', prompt: 'Sugira 5 áudios ou tendências atuais que podem ser adaptadas para o nicho de [NICHO].' },
  { id: 't31', title: 'Prompt de Resumo em Tópicos', type: 'text', preview: 'Produtividade', prompt: 'Extraia as 10 principais ideias do texto abaixo em uma lista de bullet points simples e clara: [TEXTO].' },
  { id: 't32', title: 'Gerador de Nomes de Marca', type: 'text', preview: 'Outro', prompt: 'Sugira 15 nomes curtos e modernos para uma empresa que trabalha com [SETOR]. Explique o conceito.' },
  { id: 't33', title: 'Roteiro de Vendas Direta', type: 'text', preview: 'Vendas', prompt: 'Crie um pitch de vendas de elevador (elevator pitch) para o produto [PRODUTO]. Duração: 45 segundos.' },
  { id: 't34', title: 'E-mail de Follow-up', type: 'text', preview: 'Trabalho', prompt: 'Escreva um e-mail educado cobrando uma resposta sobre a proposta enviada há 3 dias. Sem ser invasivo.' },
  { id: 't35', title: 'Debate de Argumentos', type: 'text', preview: 'Estudos', prompt: 'Forneça 5 argumentos a favor e 5 argumentos contra o tema [TEMA]. Seja imparcial e profundo.' },
  { id: 't36', title: 'Criação de Personagem', type: 'text', preview: 'Outro', prompt: 'Crie um perfil psicológico detalhado para um vilão de uma história de [GÊNERO]. Inclua motivações e medos.' },
  { id: 't37', title: 'Review de Produto Tech', type: 'text', preview: 'Marketing', prompt: 'Escreva um review honesto e detalhado sobre o [DISPOSITIVO], focando em usabilidade e custo-benefício.' },
  { id: 't38', title: 'Plano de Ação 24h', type: 'text', preview: 'Produtividade', prompt: 'Estou sobrecarregado. Tenho as tarefas: [LISTA]. Crie um plano de ataque para concluir tudo em 24h.' },
  { id: 't39', title: 'Script de Vídeo Institucional', type: 'text', preview: 'Marketing', prompt: 'Escreva o roteiro de locução para um vídeo de 2 minutos apresentando a história da empresa [NOME].' },
  { id: 't40', title: 'Tradução para Linguagem Simples', type: 'text', preview: 'Outro', prompt: 'Transforme esse contrato/documento jurídico em um texto que qualquer pessoa entenda facilmente.' },
  { id: 't41', title: 'Ideias de Títulos de Ebook', type: 'text', preview: 'Marketing', prompt: 'Sugira 10 títulos magnéticos para um ebook que ensina a [RESULTADO]. Foco em curiosidade.' },
  { id: 't42', title: 'Post Acadêmico LinkedIn', type: 'text', preview: 'Social', prompt: 'Resuma o estudo científico [TEMA] para um público de profissionais do LinkedIn. Use tom sério.' },
  { id: 't43', title: 'Prompt de Reclamação Formal', type: 'text', preview: 'Outro', prompt: 'Escreva uma reclamação formal para a empresa [NOME] sobre o problema [PROBLEMA]. Exija uma solução.' },
  { id: 't44', title: 'Checklist de Lançamento', type: 'text', preview: 'Marketing', prompt: 'Crie um checklist passo a passo para o lançamento de um [PRODUTO DIGITAL]. Do dia -30 ao dia 0.' },
  { id: 't45', title: 'Analista de Feedback de Cliente', type: 'text', preview: 'Trabalho', prompt: 'Analise essas 20 avaliações de clientes e identifique os 3 problemas recorrentes: [AVALIAÇÕES].' },
  { id: 't46', title: 'Prompt de Brainstorming Livre', type: 'text', preview: 'Criatividade', prompt: 'Gere 30 ideias loucas e inovadoras para resolver o problema de [PROBLEMA]. Não se limite ao óbvio.' },
  { id: 't47', title: 'Script de Fechamento de Venda', type: 'text', preview: 'Vendas', prompt: 'Como conduzir os últimos 5 minutos de uma reunião para garantir o fechamento do contrato hoje?' },
  { id: 't48', title: 'Bio de Palestrante', type: 'text', preview: 'Trabalho', prompt: 'Escreva uma biografia de 150 palavras focada em autoridade e experiência para o palestrante [NOME].' },
  { id: 't49', title: 'Post Engajamento Pergunta', type: 'text', preview: 'Social', prompt: 'Crie 10 perguntas polêmicas ou curiosas sobre o nicho de [NICHO] para gerar comentários no Instagram.' },
  { id: 't50', title: 'Roteiro de Reels "POV"', type: 'text', preview: 'Social', prompt: 'Crie um roteiro de POV (Point of View) engraçado sobre o cotidiano de um [PROFISSÃO].' },
  { id: 't51', title: 'Analista de Tendências', type: 'text', preview: 'Marketing', prompt: 'Quais são as 5 tendências que vão dominar o mercado de [SETOR] nos próximos 2 anos?' },
  { id: 't52', title: 'E-mail de Reativação', type: 'text', preview: 'Vendas', prompt: 'Escreva um e-mail para clientes que não compram há 6 meses. Ofereça um incentivo especial.' },
  { id: 't53', title: 'Gerador de Slogans', type: 'text', preview: 'Marketing', prompt: 'Gere 15 slogans curtos e memoráveis para uma marca que preza por [VALOR PRINCIPAL].' },
  { id: 't54', title: 'Resumo de Podcast (Notas)', type: 'text', preview: 'Produtividade', prompt: 'Transforme a transcrição abaixo em notas de rodapé organizadas por temas e horários: [TEXTO].' },
  { id: 't55', title: 'Prompt de Resolução de Conflitos', type: 'text', preview: 'Trabalho', prompt: 'Como abordar um colaborador que está performando abaixo do esperado de forma humana e motivadora?' },
  { id: 't56', title: 'Script de Upsell', type: 'text', preview: 'Vendas', prompt: 'O cliente acabou de comprar o [PRODUTO A]. Como oferecer o [PRODUTO B] como um complemento perfeito?' },
  { id: 't57', title: 'Expert em Narrativa de Vendas', type: 'text', preview: 'Vendas', prompt: 'Crie uma história curta sobre um cliente que saiu do ponto A (dor) ao ponto B (sucesso) com o [PRODUTO].' },
  { id: 't58', title: 'Prompt de Desafio 7 Dias', type: 'text', preview: 'Marketing', prompt: 'Crie um desafio de 7 dias para engajar minha audiência. Cada dia deve ter uma tarefa simples.' },
  { id: 't59', title: 'Gerador de Hooks de Blog', type: 'text', preview: 'Marketing', prompt: 'Crie 10 títulos de posts de blog usando a técnica "Clickbait Ético" sobre o tema [TEMA].' },
  { id: 't60', title: 'Analista de Concorrência', type: 'text', preview: 'Marketing', prompt: 'Liste os 3 principais concorrentes de [NEGÓCIO] e diga qual o diferencial competitivo que podemos usar.' },
  { id: 't61', title: 'Roteiro de Tour Virtual', type: 'text', preview: 'Outro', prompt: 'Escreva o texto de narração para um tour virtual de um imóvel de luxo. Foco em detalhes e emoção.' },
  { id: 't62', title: 'Prompt de Meditação Guiada', type: 'text', preview: 'Outro', prompt: 'Escreva um roteiro de 5 minutos para uma meditação focada em reduzir a ansiedade antes do trabalho.' },
  { id: 't63', title: 'E-mail de Boas-vindas', type: 'text', preview: 'Marketing', prompt: 'Escreva o primeiro e-mail que um novo assinante da minha lista deve receber. Gere conexão imediata.' },
  { id: 't64', title: 'Analista de Perfil de Público', type: 'text', preview: 'Marketing', prompt: 'Crie uma "Persona" detalhada para quem compra [PRODUTO]. Inclua medos, desejos e hobbies.' },
  { id: 't65', title: 'Prompt de Quiz de Vendas', type: 'text', preview: 'Vendas', prompt: 'Crie 5 perguntas de um quiz que ajuda o cliente a descobrir qual o melhor [PRODUTO] para ele.' },
  { id: 't66', title: 'Script de Tutorial Passo a Passo', type: 'text', preview: 'Estudos', prompt: 'Escreva um guia numerado sobre como fazer [TAREFA]. Seja extremamente claro e simples.' },
  { id: 't67', title: 'Prompt de Desculpas Pública', type: 'text', preview: 'Trabalho', prompt: 'Houve um erro no envio dos pedidos. Escreva um post de desculpas honesto e com a solução.' },
  { id: 't68', title: 'Ideias de Assuntos de E-mail', type: 'text', preview: 'Marketing', prompt: 'Gere 10 linhas de assunto que geram alta taxa de abertura para um e-mail sobre [TEMA].' },
  { id: 't69', title: 'Prompt de Comparação de Produtos', type: 'text', preview: 'Vendas', prompt: 'Crie uma tabela comparativa entre o [PRODUTO A] e o [PRODUTO B]. Seja justo mas destaque o nosso.' },
  { id: 't70', title: 'Roteiro de Unboxing', type: 'text', preview: 'Social', prompt: 'Escreva o roteiro para um vídeo de unboxing do [PRODUTO]. Foque na experiência sensorial da embalagem.' },
  { id: 't71', title: 'Analista de Call to Action', type: 'text', preview: 'Marketing', prompt: 'Sugira 10 variações de botões de CTA que não sejam o óbvio "Compre Agora".' },
  { id: 't72', title: 'Prompt de Resumo de Livro', type: 'text', preview: 'Estudos', prompt: 'Extraia as 3 lições mais práticas e aplicáveis do livro [NOME DO LIVRO].' },
  { id: 't73', title: 'Gerador de Tópicos para Palestra', type: 'text', preview: 'Trabalho', prompt: 'Vou dar uma palestra de 20 min sobre [TEMA]. Divida o conteúdo em 4 tópicos principais.' },
  { id: 't74', title: 'E-mail de Parceria Influencer', type: 'text', preview: 'Marketing', prompt: 'Escreva uma proposta de parceria curta e atrativa para enviar a um influenciador do nicho de [NICHO].' },
  { id: 't75', title: 'Mestre da Persuasão Final', type: 'text', preview: 'Vendas', prompt: 'Como usar o gatilho da Prova Social para converter esse cliente indeciso: [CENÁRIO].' },

  // --- 25 IMAGE TEMPLATES ---
  { id: 'i1', title: 'Retrato Realista 8K', type: 'image', preview: 'Pessoa', prompt: 'Ultra-realistic 8k portrait of a [SUBJECT], hyper-detailed skin texture, studio lighting, Hasselblad, f/1.8.' },
  { id: 'i2', title: 'Cyberpunk Metropolis', type: 'image', preview: 'Arquitetura', prompt: 'Futuristic city street at night, neon lights, rainy window view, volumetric lighting, cinematic 4k.' },
  { id: 'i3', title: 'Logo Minimalista Vetor', type: 'image', preview: 'Arte', prompt: 'Modern minimalist geometric logo for [BRAND], flat vector, white background, high contrast, clean lines.' },
  { id: 'i4', title: 'Fantasy Concept Art', type: 'image', preview: 'Arte', prompt: 'Epic landscape of a floating castle, dragons in distance, digital painting, ArtStation style, vibrant colors.' },
  { id: 'i5', title: 'Macro Natureza Viva', type: 'image', preview: 'Paisagem', prompt: 'Extreme macro shot of a [FLOWER], water drops, sunrise lighting, shallow depth of field, National Geographic style.' },
  { id: 'i6', title: 'Foto de Rua P&B', type: 'image', preview: 'Pessoa', prompt: 'Black and white street photography in New York, rain reflections, dramatic shadows, grain texture, Leica M11.' },
  { id: 'i7', title: 'E-commerce Packshot', type: 'image', preview: 'Produto', prompt: 'Professional product shot of a [PRODUCT] on glass, soft studio lighting, reflection, luxury aesthetic, clean.' },
  { id: 'i8', title: 'Interior Design Japandi', type: 'image', preview: 'Arquitetura', prompt: 'Minimalist Japandi living room, natural wood, large windows, soft morning light, 4k render, cozy.' },
  { id: 'i9', title: 'Isometric 3D Room', type: 'image', preview: 'Arte', prompt: 'Isometric 3D low poly bedroom, pastel colors, cute furniture, soft clay render, Octane render style.' },
  { id: 'i10', title: 'Vogue Fashion Editorial', type: 'image', preview: 'Pessoa', prompt: 'High fashion editorial in a desert, model wearing avant-garde clothing, dramatic pose, Vogue magazine style.' },
  { id: 'i11', title: 'Game Texture: Stone', type: 'image', preview: 'Arte', prompt: 'Procedural 4k stone wall texture, realistic moss, depth map, high resolution, gaming asset style.' },
  { id: 'i12', title: 'Underwater Bioluminescence', type: 'image', preview: 'Paisagem', prompt: 'Deep ocean floor, glowing jellyfish, mystical blue light, cinematic underwater photography, ethereal.' },
  { id: 'i13', title: 'Anúncio de Carro Luxo', type: 'image', preview: 'Produto', prompt: 'Luxury car driving on a mountain road at sunset, motion blur, commercial photography style, 8k.' },
  { id: 'i14', title: 'Ilustração Aquarela', type: 'image', preview: 'Arte', prompt: 'Soft watercolor illustration of a [SUBJECT], hand-drawn aesthetic, pastel tones, white background.' },
  { id: 'i15', title: 'Architecture Sketch', type: 'image', preview: 'Arquitetura', prompt: 'Detailed architectural pencil sketch of a modern museum, white paper, clean lines, professional.' },
  { id: 'i16', title: 'Double Exposure Art', type: 'image', preview: 'Arte', prompt: 'Double exposure portrait of a man combined with a dense forest, surrealist art, high contrast, minimal.' },
  { id: 'i17', title: 'Vintage 1950s Poster', type: 'image', preview: 'Arte', prompt: 'Mid-century modern travel poster for [CITY], flat colors, retro typography, vintage aesthetic.' },
  { id: 'i18', title: 'Space Nebula Hubble', type: 'image', preview: 'Paisagem', prompt: 'Vibrant space nebula, galaxies in background, stars, Hubble telescope style, cosmic colors, 8k.' },
  { id: 'i19', title: 'Jewelry Macro Shot', type: 'image', preview: 'Produto', prompt: 'Extreme close up of a diamond ring, sparkling light, dark background, luxury commercial style, sharp focus.' },
  { id: 'i20', title: 'Post-Apocalyptic City', type: 'image', preview: 'Arquitetura', prompt: 'Abandoned city overgrown with plants, ruins, post-apocalyptic atmosphere, cinematic lighting, The Last of Us style.' },
  { id: 'i21', title: 'Food Editorial Photo', type: 'image', preview: 'Produto', prompt: 'Platter of [FOOD], moody lighting, top down view, rustic table, food magazine aesthetic, professional.' },
  { id: 'i22', title: 'Mythical Creature Design', type: 'image', preview: 'Arte', prompt: 'Full body design of a hybrid [ANIMAL A] and [ANIMAL B], ornate details, magical aura, white background.' },
  { id: 'i23', title: 'Cyberpunk Vehicle', type: 'image', prompt: 'Produto', preview: 'Futuristic flying motorcycle, chrome finish, glowing engines, cyberpunk city background, speed lines.' },
  { id: 'i24', title: 'Glitch Art Portrait', type: 'image', preview: 'Pessoa', prompt: 'Surreal portrait with digital glitch effects, neon colors, VHS aesthetic, experimental photography.' },
  { id: 'i25', title: 'Minimalist Nature Wall', type: 'image', preview: 'Paisagem', prompt: 'Abstract minimalist landscape, mountain silhouettes, sun, earth tones, flat design style.' },
];

export const EXAMPLES: Example[] = [
  { id: 'e1', title: 'E-mail de Vendas', before: 'Faça um e-mail vendendo curso.', after: 'Atue como Copywriter. Escreva um e-mail focado na frustração de não ter resultados em [ÁREA], apresentando o curso [NOME] como a solução definitiva. Use o tom de "amigo especialista". Termine com um CTA de bônus por 24h.', improvement: 'Conversão 10x maior' },
  { id: 'e2', title: 'Imagem Futurista', before: 'Cidade no futuro.', after: 'Futuristic city street at night, neon signs in Japanese, heavy rain, reflections on asphalt, volumetric lighting, cinematic teal and orange color grade, 8k, photorealistic.', improvement: 'Nível Cinematográfico' },
  { id: 'e3', title: 'Post de Instagram', before: 'Post sobre viagem.', after: 'Escreva 3 ganchos magnéticos para um post sobre [LUGAR]. O objetivo é fazer a pessoa salvar o post para as próximas férias. Use emojis e um tom inspirador e leve.', improvement: 'Mais Salvamentos' },
];

export const COURSE_MODULES = [
  { id: 1, title: 'O que é IA?', description: 'Entendendo o assistente.', content: ['Pense na IA como um amigo que leu a internet inteira.', 'Ela não é mágica, ela apenas tenta adivinhar o que você quer.', 'Se você pedir direito, ela faz quase tudo por você.'], icon: <Zap /> },
  { id: 2, title: 'O Erro do "Genérico"', description: 'Por que o resultado é ruim.', content: ['Pedir "faça um texto" é como pedir "faça uma comida" num restaurante.', 'A IA precisa saber o "sabor" (o estilo) e os "ingredientes" (os detalhes).', 'Quanto mais vago você for, mais robótica ela será.'], icon: <MessageSquare /> },
  { id: 3, title: 'O Papel Mágico', description: 'Dando uma profissão.', content: ['Sempre diga quem a IA é: "Seja um Professor", "Seja um Nutricionista".', 'Isso muda a forma como ela escreve e os exemplos que ela usa.', 'É o passo mais importante para um prompt de elite.'], icon: <Compass /> },
  { id: 4, title: 'O Alvo: Objetivo', description: 'O que você quer ganhar?', content: ['Diga o que você quer no final: um e-mail? Uma lista? Uma tabela?', 'Diga para quem é o texto: para seu chefe? Para seu filho?', 'Um alvo claro evita que a IA enrole no texto.'], icon: <Target /> },
  { id: 5, title: 'A Moldura: Formato', description: 'Como a resposta chega.', content: ['Você pode pedir em tópicos, em negrito ou até em código.', 'Diga se quer o texto curto (para WhatsApp) ou longo (para um Blog).', 'O formato ajuda você a só copiar e colar.'], icon: <Layers /> },
  { id: 6, title: 'Luz, Câmera e IA!', description: 'Gerando imagens.', content: ['Para fotos, você é o fotógrafo. Fale da luz (sol, neon).', 'Fale do estilo (foto real, desenho, pintura).', 'Diga se quer ver de perto (macro) ou de longe (grande angular).'], icon: <Eye /> },
  { id: 7, title: 'A Segunda Chance', description: 'Ajustando o resultado.', content: ['Quase nunca o primeiro resultado é perfeito.', 'Diga: "Gostei, mas mude o tom" ou "Adicione mais 2 exemplos".', 'É conversando que você chega na perfeição.'], icon: <Repeat /> },
  { id: 8, title: 'Segurança Primeiro', description: 'O que não postar.', content: ['Nunca coloque sua senha ou endereço real nos prompts.', 'A IA pode errar fatos. Sempre dê uma olhada antes de postar algo importante.', 'Use para ter ideias, não para substituir seu cérebro.'], icon: <Shield /> },
  { id: 9, title: 'Hora de Praticar!', description: 'Seu próximo passo.', content: ['Use as ferramentas aqui do Studio para criar seus primeiros prompts.', 'Copie nossos templates e mude as partes entre colchetes.', 'Você já está à frente de 90% das pessoas!'], icon: <Trophy /> }
];
